name: frist_flutter_app # 应用或包名
description: A new Flutter application. # 应用或包的描述、简介

version: 1.0.0+1    # 应用或包的版本号

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:      # 应用或包依赖的其他包或插件
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  english_words: ^3.1.3   # 新添加的包，第一次添加之后需要在命令行运行 flutter packages get 将包下载到本地

dev_dependencies: # 开发环境依赖的工具包（不是flutter本身依赖的包）
  flutter_test:
    sdk: flutter

flutter:            # flutter 的相关配置选项
  uses-material-design: true
  assets:
    - images/my_icon.png
#  fonts:
#    - family: Raleway
#    fonts:
#      - asset: assets/fonts/Raleway-Regular.ttf
#      - asset: assets/fonts/Raleway-Medium.ttf
#      weight: 500
#      - asset: assets/fonts/Raleway-SemiBold.ttf
#      weight: 600
#    - family: AbriFatface
#    fonts:
#      - asset: assets/fonts/abrilfatface/AbrilFatface-Regular.ttf
